-- UG Collection — esquema MySQL / MariaDB
-- Cada fila guarda el documento JSON tal como lo usa el sitio (flexible y fácil de exportar).

CREATE TABLE IF NOT EXISTS ug_settings (
  id TINYINT UNSIGNED NOT NULL PRIMARY KEY DEFAULT 1,
  data LONGTEXT NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ug_collections (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  sort INT NOT NULL DEFAULT 0,
  data LONGTEXT NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ug_products (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  sort INT NOT NULL DEFAULT 0,
  data LONGTEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_sort (sort)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Usuario administrador (una sola cuenta; se cambia desde el panel → Ajustes)
CREATE TABLE IF NOT EXISTS ug_admin (
  id TINYINT UNSIGNED NOT NULL PRIMARY KEY DEFAULT 1,
  user VARCHAR(40) NOT NULL,
  pass_hash VARCHAR(255) NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Intentos de login (protección contra fuerza bruta)
CREATE TABLE IF NOT EXISTS ug_login_attempts (
  ip VARCHAR(45) NOT NULL,
  at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_ip_at (ip, at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
